<?php

use Illuminate\Database\Seeder;
// modelo
use App\Models\Service;

class ServicesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    $arrayService = [
        
      
        [
          "id"=>"4",
          "package_name"=>"PACK INICIAL 1K 💻",
          "categories_id"=>"1",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"40",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"13",
          "description"=>"<p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><br></p><p>Descripcion:&nbsp;gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.</p><p>Velocidad:&nbsp;El tiempo de entrega de este servicio es 4&nbsp;a 8 días.</p><p><br></p><p>//Pasos a seguir:</p><p>Link=>agrege su usuario de instagram sin el simbolo @.</p><p>Se inicia el servicio 24 a 48 horas después de la compra.</p><p>Recibirás una confirmación de pedido en tu email.</p><p><br></p><p><strong>SU PERFIL DEBE ESTAR PUBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAD O PAÍS LATINO</strong></p><p><br></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p><p><strong><em>Si cambias tu usuario de instagram en pleno proceso tu paquete se dará por terminado.</em></strong></p>",
          "created_at"=>"2021-01-29 08:29:06",
          "updated_at"=>"2021-03-25 01:24:40"
        ],
        [
          "id"=>"7",
          "package_name"=>"MINI MEDIA 3K 💻",
          "categories_id"=>"1",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"90",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"14",
          "description"=>"<p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.<br><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es 8&nbsp;a 18&nbsp;días.<br><br><strong>//Pasos a seguir:</strong><br><strong>Link=>agrege su usuario de instagram sin el simbolo @.</strong><br><br><strong>Recibirás una confirmación de pedido en tu email.</strong></p><p><strong>​​​​Se inicia el paquete en 24 a 48 horas después de la confirmación de compra.</strong></p><p><strong>SU PERFIL DEBE ESTAR PUBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAD O PAÍS LATINO.</strong></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p><div class=\"modal-body\"><div class=\"form-body\"><div class=\"row justify-content-md-center\"><div class=\"col-md-12 col-sm-12 col-xs-12\"><div class=\"form-group\"><div class=\"content\">    \r\n\r\n                  </div>\r\n                </div>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>",
          "created_at"=>"2021-01-29 09:53:37",
          "updated_at"=>"2021-03-25 01:28:26"
        ],
        [
          "id"=>"9",
          "package_name"=>"VISION MEDIA 20K 💻🌟🔷",
          "categories_id"=>"1",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"460",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"17",
          "description"=>"<div class=\"modal-body\"><div class=\"form-body\"><div class=\"row justify-content-md-center\"><div class=\"col-md-12 col-sm-12 col-xs-12\"><p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><strong>Descripcion=></strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.<br><strong>Velocidad=></strong>El tiempo de entrega de este servicio es 45 a 60 días.<br><br><strong>//Pasos a seguir:</strong><br><strong>Link=>agrege su usuario de instagram sin el simbolo @.</strong><br><br><strong>Recibirás una confirmación de pedido en tu email.</strong></p><p><strong>SU PERFIL DEBE ESTAR PÚBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAS O PAÍS LATINO.</strong></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p><div class=\"form-group\"><div class=\"content\">    \r\n\r\n                  </div>\r\n                </div>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>",
          "created_at"=>"2021-01-29 08:29:06",
          "updated_at"=>"2021-03-25 01:38:50"
        ],
        [
          "id"=>"10",
          "package_name"=>"GOLD MEDIA 10K 💻🌟",
          "categories_id"=>"1",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"250",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"16",
          "description"=>"<p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><strong>Descripcion=></strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.<br><strong>Velocidad=></strong>El tiempo de entrega de este servicio es 35 a 50&nbsp;días.<br><br><strong>//Pasos a seguir:</strong><br><strong>Link=>agrege su usuario de instagram sin el simbolo @.</strong><br><br><strong>Recibirás una confirmación de pedido en tu email.</strong></p><p><strong>​​​​Se inicia el paquete en 24 a 48 horas después de la confirmación de compra</strong></p><p><strong>SU PERFIL DEBE ESTAR PÚBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAS O PAÍS LATINO.</strong></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p><div class=\"modal-body\"><div class=\"form-body\"><div class=\"row justify-content-md-center\"><div class=\"col-md-12 col-sm-12 col-xs-12\"><div class=\"form-group\"><div class=\"content\">    \r\n\r\n                  </div>\r\n                </div>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>",
          "created_at"=>"2021-01-29 09:53:37",
          "updated_at"=>"2021-03-25 01:36:32"
        ],
        [
          "id"=>"11",
          "package_name"=>"DIAMOND MEDIA 50K 💻💎💎",
          "categories_id"=>"1",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"1100",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"18",
          "description"=>"<p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><strong>Descripcion=></strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.<br><strong>Velocidad=></strong>El tiempo de entrega de este servicio es 60 a 90 días.<br><br><strong>//Pasos a seguir:</strong><br><strong>Link=>agrege su usuario de instagram sin el simbolo @.</strong><br><br><strong>Recibirás una confirmación de pedido en tu email.</strong></p><p><strong>SU PERFIL DEBE ESTAR PÚBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAS O PAÍS LATINO.</strong></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p><div class=\"modal-body\"><div class=\"form-body\"><div class=\"row justify-content-md-center\"><div class=\"col-md-12 col-sm-12 col-xs-12\"><div class=\"form-group\"><div class=\"content\">    \r\n\r\n                  </div>\r\n                </div>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>",
          "created_at"=>"2021-01-29 09:53:37",
          "updated_at"=>"2021-03-25 01:41:39"
        ],
        [
          "id"=>"12",
          "package_name"=>"SILVER MEDIA 5K 💻❤",
          "categories_id"=>"1",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"135",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"15",
          "description"=>"<p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.<br><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es 20 a 30&nbsp;días.<br><br><strong>//Pasos a seguir:</strong><br><strong>Link=>agrege su usuario de instagram sin el simbolo @.<br><br>Recibirás una confirmación de pedido en tu email.</strong></p><p><strong>​​​​Se inicia el paquete en 24 a 48 horas después de la confirmación de compra</strong></p><p><strong>SU PERFIL DEBE ESTAR PUBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAD O PAÍS LATINO.</strong></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p><p><br data-cke-eol=\"1\"></p><div class=\"modal-body\"><div class=\"form-body\"><div class=\"row justify-content-md-center\"><div class=\"col-md-12 col-sm-12 col-xs-12\"><div class=\"form-group\"><div class=\"content\">    \r\n\r\n                  </div>\r\n                </div>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>",
          "created_at"=>"2021-01-29 09:53:37",
          "updated_at"=>"2021-03-25 01:35:03"
        ],
        [
          "id"=>"13",
          "package_name"=>"ELITE MEDIA 100K 💻⚡️⚡️🔥",
          "categories_id"=>"1",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"2000",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"19",
          "description"=>"<div class=\"modal-body\"><div class=\"form-body\"><div class=\"row justify-content-md-center\"><div class=\"col-md-12 col-sm-12 col-xs-12\"><p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.<br><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es 4 a 6 meses.<br><br><strong>//Pasos a seguir:</strong><br><strong>Link=>agrege su usuario de instagram sin el simbolo @.</strong><br><br><strong>Recibirás una confirmación de pedido en tu email.</strong></p><p><strong>SU PERFIL DEBE ESTAR PÚBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAS O PAÍS LATINO.</strong></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p><div class=\"form-group\"><div class=\"content\">    \r\n\r\n                  </div>\r\n                </div>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>",
          "created_at"=>"2021-01-29 08:29:06",
          "updated_at"=>"2021-03-25 01:43:14"
        ],
        [
          "id"=>"15",
          "package_name"=>"MANAGERS+MIL SEGUIDORES",
          "categories_id"=>"24",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"70",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"1",
          "description"=>"<p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><br></p><p>Descripcion:&nbsp;gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.</p><p>Velocidad:&nbsp;El tiempo de entrega de este servicio es 3 a 5 días.</p><p><br></p><p>//Pasos a seguir:</p><p>Link=>agrege su usuario de instagram sin el simbolo @.</p><p><br></p><p>Recibirás una confirmación de pedido en tu email.</p><p><br></p><p><strong>SU PERFIL DEBE ESTAR PUBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAD O PAÍS LATINO</strong></p><p><br></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO&nbsp;</strong></p><p><strong>El cupon de viralmanager llegará directamente a tu correo electrónico para canjearlo sigue los tutoriales que se indican en el correo y regístrate en viralmanagers.com</strong></p>",
          "created_at"=>"2021-03-25 01:14:20",
          "updated_at"=>"2021-03-25 01:14:20"
        ],
        [
          "id"=>"16",
          "package_name"=>"3k SEGUIDORES+ 1.500 LIKES",
          "categories_id"=>"24",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"85",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"2",
          "description"=>"<p><br></p><p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.<br><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es 6 a 12 días.<br><br><strong>//Pasos a seguir:</strong><br><strong>Link=>agrege su usuario de instagram sin el simbolo @.</strong><br><br><strong>Recibirás una confirmación de pedido en tu email.</strong></p><p><strong>SU PERFIL DEBE ESTAR PUBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAD O PAÍS LATINO.</strong></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p>",
          "created_at"=>"2021-03-25 01:15:28",
          "updated_at"=>"2021-03-25 01:16:20"
        ],
        [
          "id"=>"17",
          "package_name"=>"5k SEGUIDORES+ 2.000 LIKES",
          "categories_id"=>"24",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"125",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"3",
          "description"=>"<p><strong>IMPORTANTE LEA PASOS A SEGUIR</strong></p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y latinos.<br><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es 15 a 25 días.<br><br><strong>//Pasos a seguir:</strong><br><strong>Link=>agrege su usuario de instagram sin el simbolo @.<br><br>Recibirás una confirmación de pedido en tu email.</strong></p><p><strong>SU PERFIL DEBE ESTAR PUBLICO Y NO TENER NINGUNA RESTRICCIÓN DE EDAD O PAÍS LATINO.</strong></p><p><strong>SI EL ESTADO DE TU PEDIDO APARECE COMPLETADO ES PORQUE EL SISTEMA YA RECIBIÓ TU ORDEN Y SE ENCUENTRA EN PROCESO.</strong></p>",
          "created_at"=>"2021-03-25 01:16:10",
          "updated_at"=>"2021-03-25 01:16:10"
        ],
        [
          "id"=>"18",
          "package_name"=>"Instagram Likes  [desde 50 / hasta 100K]  ❤ Alta Calidad",
          "categories_id"=>"3",
          "minimum_amount"=>"50",
          "maximum_amount"=>"100000",
          "price"=>"6.2",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"1916",
          "description"=>"<p><br></p><ol><li>El tiempo estimado de inicio para ver los resultados de este servicio es de 0 a 24 horas.</li><li><strong>Compra</strong>=>la compra minima de este servicio es de 50 likes hasta 10.000 likes.&nbsp;</li><li>Podras usar este servicio para obtener likes en tus videos,fotos y IGTV de Instagram.</li><li>Pueden llegar de 0 a 5% más&nbsp;</li><li>Sirven para posicionar las publicaciones en motores de búsqueda</li><li>Tu perfil debe ser público para poder recibir la orden satisfactoriamente.</li><li>No realizar mas de una orden de likes para la misma publicación mientras otra orden se encuentre activa.</li></ol><p><br></p>",
          "created_at"=>"2021-03-25 01:17:30",
          "updated_at"=>"2021-03-25 01:47:43"
        ],
        [
          "id"=>"19",
          "package_name"=>"Instagram Likes  [desde 100 / hasta 100K] ❤ Alta Calidad Recomendados",
          "categories_id"=>"3",
          "minimum_amount"=>"100",
          "maximum_amount"=>"3000",
          "price"=>"6.5",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"3476",
          "description"=>"<ol><li>El tiempo estimado de inicio para ver los resultados de este servicio es de 0 a 24 horas.</li><li><strong>Compra</strong>=>la compra minima de este servicio es de 100&nbsp;likes hasta 10.000 likes.&nbsp;</li><li>Podras usar este servicio para obtener likes en tus videos,fotos y IGTV de Instagram.</li><li>Pueden llegar de 0 a 5% más&nbsp;</li><li>Sirven para posicionar las publicaciones en motores de búsqueda.</li><li>Tu perfil debe ser público para poder recibir la orden satisfactoriamente.</li><li>No realizar mas de una orden de likes para la misma publicación mientras otra orden se encuentre activa.</li><li>LIKES DE TODO EL MUNDO</li></ol>",
          "created_at"=>"2021-03-25 01:18:18",
          "updated_at"=>"2021-03-25 01:18:18"
        ],
        [
          "id"=>"20",
          "package_name"=>"Instagram Likes Europa ( desde 100 / 10k ) calidad alta",
          "categories_id"=>"3",
          "minimum_amount"=>"100",
          "maximum_amount"=>"10000",
          "price"=>"6.6",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"1333",
          "description"=>"<ol><li>El tiempo estimado de inicio para ver los resultados de este servicio es de 0 a 24 horas.</li><li><strong>Compra</strong>=>la compra minima de este servicio es de 100 likes hasta 10.000 likes.&nbsp;</li><li>Podras usar este servicio para obtener likes en tus videos,fotos y IGTV de Instagram.</li><li>Pueden llegar de 0 a 5% más&nbsp;</li><li>Sirven para posicionar las publicaciones en motores de búsqueda</li></ol>",
          "created_at"=>"2021-03-25 01:20:03",
          "updated_at"=>"2021-03-25 01:20:03"
        ],
        [
          "id"=>"21",
          "package_name"=>"PACK INICIAL 1K 💻",
          "categories_id"=>"1",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"1000",
          "price"=>"40",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"Manual",
          "api_provide_name"=>"null",
          "api_service_id"=>"null",
          "description"=>"null",
          "created_at"=>"2021-03-25 01:25:46",
          "updated_at"=>"2021-03-25 01:25:46"
        ],
        [
          "id"=>"22",
          "package_name"=>"MINI MEDIA 3K  💻",
          "categories_id"=>"1",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"1000",
          "price"=>"90",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"Manual",
          "api_provide_name"=>"null",
          "api_service_id"=>"null",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es aprox de 1 mes.</p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y segmentados en tu region.</p><p><br></p><p><strong>NOTA:&nbsp;</strong>una vez adquieres el servicio debes abrir un ticket a soporte para que inicie el servicio.</p>",
          "created_at"=>"2021-03-25 01:27:52",
          "updated_at"=>"2021-03-25 01:27:52"
        ],
        [
          "id"=>"23",
          "package_name"=>"SILVER MEDIA 5K 💻❤",
          "categories_id"=>"1",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"1000",
          "price"=>"135",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"Manual",
          "api_provide_name"=>"null",
          "api_service_id"=>"null",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es aprox de 1 mes.</p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y segmentados en tu region.</p><p><br></p><p><strong>NOTA:&nbsp;</strong>una vez adquieres el servicio debes abrir un ticket a soporte para que inicie el servicio.</p>",
          "created_at"=>"2021-03-25 01:34:26",
          "updated_at"=>"2021-03-25 01:34:26"
        ],
        [
          "id"=>"24",
          "package_name"=>"GOLD MEDIA 10K 💻🌟",
          "categories_id"=>"1",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"1000",
          "price"=>"250",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"Manual",
          "api_provide_name"=>"null",
          "api_service_id"=>"null",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es aprox de 1 mes.</p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y segmentados en tu region.</p><p><br></p><p><strong>NOTA:&nbsp;</strong>una vez adquieres el servicio debes abrir un ticket a soporte para que inicie el servicio.</p>",
          "created_at"=>"2021-03-25 01:37:24",
          "updated_at"=>"2021-03-25 01:37:24"
        ],
        [
          "id"=>"25",
          "package_name"=>"VISION MEDIA 20K 💻🌟🔷",
          "categories_id"=>"1",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"1000",
          "price"=>"460",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"Manual",
          "api_provide_name"=>"null",
          "api_service_id"=>"null",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es aprox de 45 Dias.</p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y segmentados en tu region.</p><p><br></p><p><strong>NOTA:&nbsp;</strong>una vez adquieres el servicio debes abrir un ticket a soporte para que inicie el servicio.</p>",
          "created_at"=>"2021-03-25 01:40:06",
          "updated_at"=>"2021-03-25 01:40:06"
        ],
        [
          "id"=>"26",
          "package_name"=>"DIAMOND MEDIA 50K 💻💎💎",
          "categories_id"=>"1",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"1000",
          "price"=>"1100",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"Manual",
          "api_provide_name"=>"null",
          "api_service_id"=>"null",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es aprox de 3&nbsp;meses.</p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y segmentados en tu region.</p><p><br></p><p><strong>NOTA:&nbsp;</strong>una vez adquieres el servicio debes abrir un ticket a soporte para que inicie el servicio.</p>",
          "created_at"=>"2021-03-25 01:40:47",
          "updated_at"=>"2021-03-25 01:40:47"
        ],
        [
          "id"=>"27",
          "package_name"=>"ELITE MEDIA 100K 💻⚡⚡🔥",
          "categories_id"=>"1",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"1000",
          "price"=>"2000",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"Manual",
          "api_provide_name"=>"null",
          "api_service_id"=>"null",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>El tiempo de entrega de este servicio es aprox de 6&nbsp;meses.</p><p><strong>Descripcion:&nbsp;</strong>gracias a nuestro panel de recomendaciones, nuestros influencer recomendaran tu perfil gracias a sorteos de obsequios que brinda viral media, esto te permitira tener seguidores 100% reales y segmentados en tu region.</p><p><br></p><p><strong>NOTA:&nbsp;</strong>una vez adquieres el servicio debes abrir un ticket a soporte para que inicie el servicio.</p>",
          "created_at"=>"2021-03-25 01:42:20",
          "updated_at"=>"2021-03-25 01:42:20"
        ],
        [
          "id"=>"28",
          "package_name"=>"Instagram Reproducciones IGTV [desde 1k / hasta 5M] 💻👀",
          "categories_id"=>"5",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"5000000",
          "price"=>"0.85",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"735",
          "description"=>"<ol><li><strong>Velocidad=></strong>Speed fast (velocidad rapidad) 0 a 12 horas.</li><li><strong>Descripcion:&nbsp;</strong>visitas IGTV 100% reales, podras usar este servicio para aumentar las visitas de tus videos IGTV.</li><li><strong>compra minima:&nbsp;&nbsp;</strong>100 visitas hasta 5 millones de visitas.</li></ol>",
          "created_at"=>"2021-03-25 01:49:52",
          "updated_at"=>"2021-03-25 01:49:52"
        ],
        [
          "id"=>"29",
          "package_name"=>"Instagram Reproducciones IGTV [desde 500 / hasta 5M]💻👀",
          "categories_id"=>"5",
          "minimum_amount"=>"500",
          "maximum_amount"=>"5000000",
          "price"=>"0.9",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"null",
          "api_service_id"=>"735",
          "description"=>"<ol><li><strong>Velocidad=></strong>Speed fast (velocidad rapidad) 0 a 12 horas.</li><li><strong>Descripcion:&nbsp;</strong>visitas IGTV 100% reales, podras usar este servicio para aumentar las visitas de tus videos IGTV.</li><li><strong>compra minima:&nbsp;&nbsp;</strong>500 visitas hasta 5 millones de visitas.<br></li></ol>",
          "created_at"=>"2021-03-25 01:50:52",
          "updated_at"=>"2021-03-25 01:50:52"
        ],
        [
          "id"=>"30",
          "package_name"=>"Instagram  Reproducciones Videos [desde 1k / hasta 5M] 🎥🌟",
          "categories_id"=>"6",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"5000000",
          "price"=>"0.9",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"4162",
          "description"=>"<p><br></p><ol><li><strong>Velocidad:&nbsp;</strong>el servicio tardara en iniciar de 0 a 24 horas con un maximo de 500.000 reproducciones por dia.</li><li><strong>Descripcion:&nbsp;</strong>podras comprar este servicio para aumentar las reproducciones en tus videos de facebook la compra minima de esta promocion es de 1.000 reproducciones hasta 5 millones de reproducciones en tu facebook.</li><li><strong>NOTA IMPORTANTE:&nbsp;</strong>al subir tu link del video debes pegar directamente el enlace desde tu pc, no soporta el servicio link del celular.</li></ol><p><br></p>",
          "created_at"=>"2021-03-25 01:51:43",
          "updated_at"=>"2021-03-25 01:52:04"
        ],
        [
          "id"=>"31",
          "package_name"=>"INSTAGRAM Saves",
          "categories_id"=>"7",
          "minimum_amount"=>"500",
          "maximum_amount"=>"50000",
          "price"=>"0.85",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"901",
          "description"=>"<ol><li>El tiempo estimado de inicio para ver los resultados de este servicio es de 0 a 24 horas.</li><li><strong>Compra</strong>=>la compra minima de este servicio es de 500 saves hasta 50.000 saves.</li><li>Podras usar este servicio para obtener saves en tus videos,fotos y IGTV de Instagram.</li><li>Sirven para posicionar las publicaciones en motores de búsqueda.</li><li>Tu perfil debe ser público para poder recibir la orden satisfactoriamente.</li><li>No realizar mas de una orden de saves para la misma publicación mientras otra orden se encuentre activa.</li><li>SAVES DE TODO EL MUNDO</li></ol>",
          "created_at"=>"2021-03-25 01:53:26",
          "updated_at"=>"2021-03-25 01:53:26"
        ],
        [
          "id"=>"32",
          "package_name"=>"Instagram Impresiones [ desde 500 / hasta 90k] 😳👀",
          "categories_id"=>"8",
          "minimum_amount"=>"500",
          "maximum_amount"=>"1000000",
          "price"=>"0.6",
          "status"=>"0",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"414",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>velocidad de 0 a 6 horas.<br></p>",
          "created_at"=>"2021-03-25 01:55:22",
          "updated_at"=>"2021-03-25 01:55:22"
        ],
        [
          "id"=>"33",
          "package_name"=>"Instagram Impresiones [ desde 100/ hasta 90k] 😳👀",
          "categories_id"=>"8",
          "minimum_amount"=>"100",
          "maximum_amount"=>"90000",
          "price"=>"0.65",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"414",
          "description"=>"null",
          "created_at"=>"2021-03-25 01:56:38",
          "updated_at"=>"2021-03-25 01:56:38"
        ],
        [
          "id"=>"34",
          "package_name"=>"Instagram Reel visitas (10M)",
          "categories_id"=>"9",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"100000000",
          "price"=>"0.85",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"2",
          "api_service_id"=>"1923",
          "description"=>"<p><strong>Reel visitas</strong></p><p>Estas visitas ayudan a posicionar tu reel y a llegar a muchísimas más personas</p><p>Tiempo de inicio de 0 a 12 horas</p><p>Visitas garantizadas.</p>",
          "created_at"=>"2021-03-25 01:57:51",
          "updated_at"=>"2021-03-25 01:57:51"
        ],
        [
          "id"=>"35",
          "package_name"=>"Instagram likes Reel (50k)",
          "categories_id"=>"9",
          "minimum_amount"=>"100",
          "maximum_amount"=>"50000",
          "price"=>"6",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"3527",
          "description"=>"<p><strong>Me gustas Reel</strong></p><p>me gustas que te ayudarán a posicionar tu reel son genéricos.</p><p>Tiempo de inicio de 0 a 14 horas.</p><p><br data-cke-eol=\"1\"></p>",
          "created_at"=>"2021-03-25 01:58:37",
          "updated_at"=>"2021-03-25 01:58:37"
        ],
        [
          "id"=>"36",
          "package_name"=>"1 CUENTA + VIRALDM⭐",
          "categories_id"=>"11",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"45",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"20",
          "description"=>"<p>SERVICIO HASTA 1&nbsp;CUENTA&nbsp;DE IG</p><p>Prospecta cientos de personas gracias a nuestra herramienta de Inteligencia artificial.<br>APROVECHA EL PLUS DE VIRALMANAGERS...<br>y AUTO RESPONDE MENSAJES DIRECTOS!</p><p>Pasos a seguir:</p><p>&nbsp;- Selecciona 1 tipo de membresia y<strong>&nbsp;agrega tu email&nbsp;</strong>en el campo Link.</p><p>&nbsp;- Recibe tu cupon en tu Email una vez realizado el pago(automaticamente).</p><p>&nbsp;- Registrate en viralmanagers.com si no estas registrado.</p><p>&nbsp;- Usa tu cupon y disfruta de los resultados.</p><p><strong>NOTA=>Compruebe la escritura de&nbsp;su email&nbsp; ingresado en el campo Link.</strong></p><p><strong>Importante la herramienta te puede atraer de 5 a 10 mensajes diarios a tu bandeja de spam en Instagram si la configuras de manera adecuada.</strong></p><p><strong>ViralDm se encarga de responder mensajes que te llegan a tu bandeja de spam.</strong></p>",
          "created_at"=>"2021-03-25 01:59:50",
          "updated_at"=>"2021-03-25 01:59:50"
        ],
        [
          "id"=>"37",
          "package_name"=>"2 CUENTAS + VIRALDM ⭐⭐",
          "categories_id"=>"11",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"90",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"21",
          "description"=>"<p>SERVICIO HASTA 2&nbsp;CUENTAS&nbsp;DE IG</p><p>Prospecta cientos de personas gracias a nuestra herramienta de Inteligencia artificial.<br>APROVECHA EL PLUS DE VIRALMANAGERS...<br>y AUTO RESPONDE MENSAJES DIRECTOS!</p><p>Pasos a seguir:</p><p>&nbsp;- Selecciona 1 tipo de membresia y<strong>&nbsp;agrega tu email&nbsp;</strong>en el campo Link.</p><p>&nbsp;- Recibe tu cupon en tu Email una vez realizado el pago(automaticamente).</p><p>&nbsp;- Registrate en viralmanagers.com si no estas registrado.</p><p>&nbsp;- Usa tu cupon y disfruta de los resultados.</p><p><strong>NOTA=>Compruebe la escritura de&nbsp;su email&nbsp; ingresado en el campo Link.</strong></p><p><strong>Importante la herramienta te puede atraer de 5 a 10 mensajes diarios a tu bandeja de spam en Instagram si la configuras de manera adecuada.</strong></p><p>ViralDm se encarga de responder mensajes que te llegan a tu bandeja de spam.</p><p><strong>​​​</strong></p>",
          "created_at"=>"2021-03-25 02:00:36",
          "updated_at"=>"2021-03-25 02:00:36"
        ],
        [
          "id"=>"38",
          "package_name"=>"4 CUENTAS + VIRALDM ⭐⭐⭐",
          "categories_id"=>"11",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"180",
          "status"=>"1",
          "type_services"=>"package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"22",
          "description"=>"<p>SERVICIO HASTA 4&nbsp;CUENTAS&nbsp;DE IG</p><p>Prospecta cientos de personas gracias a nuestra herramienta de Inteligencia artificial.<br>APROVECHA EL PLUS DE VIRALMANAGERS...<br>y AUTO RESPONDE MENSAJES DIRECTOS!</p><p>Pasos a seguir:</p><p>&nbsp;- Selecciona 1 tipo de membresia y<strong>&nbsp;agrega tu email&nbsp;</strong>en el campo Link.</p><p>&nbsp;- Recibe tu cupon en tu Email una vez realizado el pago(automaticamente).</p><p>&nbsp;- Registrate en viralmanagers.com si no estas registrado.</p><p>&nbsp;- Usa tu cupon y disfruta de los resultados.</p><p><strong>NOTA=>Compruebe la escritura de&nbsp;su email&nbsp; ingresado en el campo Link.</strong></p><p><br></p><p><strong>Importante la herramienta te puede atraer de 5 a 10 mensajes diarios a tu bandeja de spam en Instagram si la configuras de manera adecuada.</strong></p><p>ViralDm se encarga de responder mensajes que te llegan a tu bandeja de spam.</p><p><strong>​</strong></p>",
          "created_at"=>"2021-03-25 02:01:31",
          "updated_at"=>"2021-03-25 02:01:31"
        ],
        [
          "id"=>"39",
          "package_name"=>"Guia personalizada",
          "categories_id"=>"13",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"1000",
          "price"=>"20",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"Manual",
          "api_provide_name"=>"null",
          "api_service_id"=>"null",
          "description"=>"<p>Este servicio se encargará de guiarte y hacer la configuración correcta de VIRAL MEDIA MANAGER por ti, al comprar este servicio comunícate con soporte en línea para agendar una video llamada donde nuestro equipo de expertos en marketing digital junto a ti determinara dicha configuración según tus preferencias y público objetivo, con un acompañamiento constante en el tiempo que la herramienta permanezca activa.&nbsp;</p><p>NOTA=>Adquiere este servicio únicamente si ya compraste tu herramienta Viral Managers, luego comunícate con el equipo de soporte en línea para agendar tu video llamada.</p><p><br></p><p><strong>En link =>escribir tu correo&nbsp;</strong></p><p><strong>En cantidad =>1000&nbsp;</strong></p><p><strong>una vez compres comunícate con soporte. Activo de 9 AM a 7 PM hora Colombia</strong></p>",
          "created_at"=>"2021-03-25 02:02:51",
          "updated_at"=>"2021-03-25 02:02:51"
        ],
        [
          "id"=>"40",
          "package_name"=>"Facebook Vistas Videos [desde 300 / hasta 5M] 🎥",
          "categories_id"=>"14",
          "minimum_amount"=>"500",
          "maximum_amount"=>"5000000",
          "price"=>"0.85",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"1708",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>el servicio tardara en iniciar de 0 a 72 horas con un maximo de 500.000 reproducciones por dia.</p><p><strong>Descripcion:&nbsp;</strong>podras comprar este servicio para aumentar las reproducciones en tus videos de facebook la compra minima de esta promocion es de 300 reproducciones hasta 5 millones de reproducciones en tu facebook.</p><p><br></p><p><strong>NOTA IMPORTANTE:&nbsp;</strong>al subir tu link del video debes pegar directamente el enlace desde tu pc, no soporta&nbsp; link del celular.</p>",
          "created_at"=>"2021-03-25 02:04:56",
          "updated_at"=>"2021-03-25 02:04:56"
        ],
        [
          "id"=>"41",
          "package_name"=>"Facebook Seguidores Fanspage [ desde 200/ hasta 1k] :+1:🔷🌟",
          "categories_id"=>"15",
          "minimum_amount"=>"200",
          "maximum_amount"=>"5000",
          "price"=>"50",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"3",
          "api_service_id"=>"272",
          "description"=>"<p><strong>Velocidad:&nbsp;</strong>tiempo de inicio de 0 a 48 horas.</p><p><strong>Descripcion:&nbsp;</strong>compra este servicio para aumentar los me gusta en tus fanspage, la compra es de 200 hasta 5000 me gusta en tu fanspage.</p><p><strong>NOTA=></strong>&nbsp;los seguidores una ves entregados no tendra reembolso.&nbsp;</p>",
          "created_at"=>"2021-03-25 02:05:53",
          "updated_at"=>"2021-03-25 02:05:53"
        ],
        [
          "id"=>"42",
          "package_name"=>"Facebook Like Fotos fans page [desde 100/ hasta 500] :+1:🔷",
          "categories_id"=>"16",
          "minimum_amount"=>"100",
          "maximum_amount"=>"500",
          "price"=>"10.5",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"2",
          "api_service_id"=>"1153",
          "description"=>"<ul><li><strong>Velocidad:&nbsp;</strong>el servicio iniciara de 0 a 24 horas con un maximo de 500 likes por publicacion.</li></ul><p><br></p><ul><li><strong>Descripcion:&nbsp;</strong>podras comprar este servicio para posicionar tus publicaciones de facebook, podras comprar desde 100&nbsp;likes hasta 500 likes por publicacion.</li></ul><p><br></p><ul><li><strong>Nota:&nbsp;</strong>La publicación en tu fan page debe ser publica.</li></ul>",
          "created_at"=>"2021-03-25 02:06:48",
          "updated_at"=>"2021-03-25 02:06:48"
        ],
        [
          "id"=>"43",
          "package_name"=>"Reproducciones Youtube  [desde 1K hasta 100M] 👀🎥",
          "categories_id"=>"17",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"10000000",
          "price"=>"6.3",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"3",
          "api_service_id"=>"115",
          "description"=>"<p><br>⭐ Patrón súper instantáneo<br>⭐ Tráfico mundial blanco 100% seguro<br>⭐ Vistas sin caída ~ (Algunos videos largos tienen menos problemas de caída)<br>⭐ Inicio=>Súper instantáneo<br>⭐ Velocidad=>Máx. Hasta 1B (6M + por día en pedidos grandes)<br><br>⭐ Las vistas se mostrarán después de la actualización de Youtube.&nbsp;Normalmente se completará instantáneamente más rápido que mostrar las vistas en video.&nbsp;\\ \"NO NECESITA PREOCUPARSE POR EL ESTADO COMPLETADO POR NO MOSTRAR VISTAS \\\"<br><br>⭐¡Mejores vistas para el uso de alimentación por goteo!<br><br>⭐Todas las vistas de Youtube no aceptan reembolsos o cancelaciones una vez que comienza la entrega en progreso.<br><br>⭐ Debe ser sin restricciones y abierto para TODOS los países<br><br>⭐Avance para este servidor=>si su video tiene restricciones o no es público, podemos ayudarlo a enviarlo al servidor en funcionamiento para mejorar las vistas<br><br>⭐Relación de caída=>baja<br><br>⭐ Pedido mínimo=>1000<br>⭐ Pedido máximo=>100000000<br><br>⭐ Si su pedido está marcado como completado y no ves que el recuento de vistas haya aumentado. Dale Me gusta a tu video y actualiza la página después de 30 segundos, aparecerán tus vistas.<br><br>⚠Debe ser sin restricciones y abierto para TODOS los países.&nbsp;Si su video rechazado se canceló, vaya a la configuración de canal y video habilitada en todo el mundo o sin restricciones antes de realizar el pedido.</p><p><strong><em>Todas las vistas de Youtube no aceptan reembolso o cancelación una vez que comienza la entrega en progreso.</em></strong></p><p><strong>Inicia de 0 a 72 horas</strong></p><p><strong>Garantía de 30 días&nbsp;</strong></p>",
          "created_at"=>"2021-03-25 02:08:00",
          "updated_at"=>"2021-03-25 02:08:00"
        ],
        [
          "id"=>"44",
          "package_name"=>"Youtube Likes Videos 🎥",
          "categories_id"=>"18",
          "minimum_amount"=>"50",
          "maximum_amount"=>"5000",
          "price"=>"17",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"2",
          "api_service_id"=>"1513",
          "description"=>"<p>Nota=>garantia de 10 dias, en caso de que los likes bajen no se realizara rembolso por la compra. Se entrega en un plazo de 0 a 48 horas.<br></p>",
          "created_at"=>"2021-03-25 02:08:57",
          "updated_at"=>"2021-03-25 02:08:57"
        ],
        [
          "id"=>"45",
          "package_name"=>"Tik Tok Views",
          "categories_id"=>"19",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"10000000",
          "price"=>"0.95",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"3",
          "api_service_id"=>"1534",
          "description"=>"<p><strong>Too fast speed</strong>=>(velocidad muy&nbsp;rapida)&nbsp;&nbsp;el tiempo estimado de inicio para ver los resultados de este servicio es de 0 a 3 horas. (maximo 500k por dia)&nbsp;</p><p><strong>Compra</strong>=>la compra minima de este servicio es de 1000&nbsp;visitas&nbsp;hasta 1.000.000 visitas.&nbsp;</p><p>Podras usar este servicio para obtener visitas Tik Tok</p>",
          "created_at"=>"2021-03-25 02:10:26",
          "updated_at"=>"2021-03-25 02:10:26"
        ],
        [
          "id"=>"46",
          "package_name"=>"TIKTOK likes videos",
          "categories_id"=>"19",
          "minimum_amount"=>"100",
          "maximum_amount"=>"50000",
          "price"=>"6",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"4174",
          "description"=>"<p><strong>-Debes colocar el enlace de tu video el cual deseas posicionar.</strong></p><p><strong>-Son likes genéricos para posicionar o impulsar tu vídeo en la red social</strong></p><p><strong>-Tiempo de inicio de 0 a 24 horas&nbsp;</strong></p><p><br data-cke-eol=\"1\"></p>",
          "created_at"=>"2021-03-25 02:11:21",
          "updated_at"=>"2021-03-25 02:11:21"
        ],
        [
          "id"=>"47",
          "package_name"=>"TikTok Seguidores desde 200 a 7k / Posicionamiento",
          "categories_id"=>"19",
          "minimum_amount"=>"200",
          "maximum_amount"=>"7000",
          "price"=>"10",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"3882",
          "description"=>"<p>✅ Garantía de 30 días<br>✅ Menos caída</p><p>- Poner URL completa por ejemplo https://www.tiktok.com/@username</p><p>estos seguidores son utilizados para posicionar el perfil y aumentar las posibilidades del algoritmo de TIKTOK</p>",
          "created_at"=>"2021-03-25 02:12:01",
          "updated_at"=>"2021-03-25 02:12:01"
        ],
        [
          "id"=>"48",
          "package_name"=>"TELEGRAM Miembros  GRUPO PUBLICO desde 300 a 25k",
          "categories_id"=>"20",
          "minimum_amount"=>"1000",
          "maximum_amount"=>"5000",
          "price"=>"7",
          "status"=>"1",
          "type_services"=>"default",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"1",
          "api_service_id"=>"818",
          "description"=>"<p><strong>Miembros GRUPO DE TELEGRAM</strong></p><p><strong>EJEMPLO DE LINK:&nbsp;</strong><strong>https://t.me/viralmediapanel</strong></p><p>- SOLO se aceptan canales</p><p>- Solo ingrese al canal USERNAME</p><p>- 1- 12 horas para comenzar</p><p>Si canale es privado no se subiran los miembros y no se hacen rembolsos respecto a eso</p><p>Este servicio es solo para posicionar tu canal son personas de todo el mundo&nbsp;<strong>no segmentados.</strong></p>",
          "created_at"=>"2021-03-25 02:12:47",
          "updated_at"=>"2021-03-25 02:12:47"
        ],
        [
          "id"=>"49",
          "package_name"=>"Edicion de fotos (+ frase + logo) x 10 📷",
          "categories_id"=>"21",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"40",
          "status"=>"1",
          "type_services"=>"custom_comments_package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"7",
          "description"=>"<p>EDITA TUS FOTOS CON NUESTRO EQUIPO DE DISEÑADORES.</p><p>pasos a seguir:<br><br>-Link=>(debes adjuntar un link de&nbsp;tus archivos de preferencia en mega en donde no solo tengas tus archivos y un archivo de texto detallando tus ideas).<br><br>-email 1=>corresponde a tu contacto para poder enviarte los diseños o contactarte de ser necesario.<br>-email 2=>en caso que no logremos contactar con usted por el primero.</p><p><strong>Importante=>Procure </strong>sus fotos con alta resolucion seguido de la frase que desees que agreguemos a la misma, para logos o firmas se agradece que tengas el formato PNG.</p>",
          "created_at"=>"2021-03-25 02:13:33",
          "updated_at"=>"2021-03-25 02:13:33"
        ],
        [
          "id"=>"50",
          "package_name"=>"Edicion de fotos (+ frase + logo) x 20 📷 🔥",
          "categories_id"=>"21",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"80",
          "status"=>"1",
          "type_services"=>"custom_comments_package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"8",
          "description"=>"<p>EDITA TUS FOTOS CON NUESTRO EQUIPO DE DISEÑADORES.</p><p>pasos a seguir:<br><br>-Link=>(debes adjuntar un link de&nbsp;tus archivos de preferencia en mega en donde no solo tengas tus archivos y un archivo de texto detallando tus ideas).<br><br>-email 1=>corresponde a tu contacto para poder enviarte los diseños o contactarte de ser necesario.<br>-email 2=>en caso que no logremos contactar con usted por el primero.</p><p><strong>Importante=>Procure </strong>sus fotos con alta resolucion seguido de la frase que desees que agreguemos a la misma, para logos o firmas se agradece que tengas el formato PNG.</p><p><br data-cke-eol=\"1\"></p>",
          "created_at"=>"2021-03-25 02:22:17",
          "updated_at"=>"2021-03-25 02:22:17"
        ],
        [
          "id"=>"51",
          "package_name"=>"Edicion de fotos (+ frase + logo) x 30 📷 🌟",
          "categories_id"=>"21",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"120",
          "status"=>"1",
          "type_services"=>"custom_comments_package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"9",
          "description"=>"<p>EDITA TUS FOTOS CON NUESTRO EQUIPO DE DISEÑADORES.<br>pasos a seguir:<br><br>-Link=>(debes adjuntar un link de&nbsp;tus archivos de preferencia en mega en donde no solo tengas tus archivos y un archivo de texto detallando tus ideas).<br><br>-email 1=>corresponde a tu contacto para poder enviarte los diseños o contactarte de ser necesario.<br>-email 2=>en caso que no logremos contactar con usted por el primeo.</p><p><strong>Importante=>Procure </strong>sus fotos con alta resolucion seguido de la frase que desees que agreguemos a la misma, para logos o firmas se agradece que tengas el formato PNG.</p>",
          "created_at"=>"2021-03-25 02:22:55",
          "updated_at"=>"2021-03-25 02:22:55"
        ],
        [
          "id"=>"52",
          "package_name"=>"Edicion de fotos (+ frase + logo) x 40 📷 ⚡",
          "categories_id"=>"21",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"150",
          "status"=>"1",
          "type_services"=>"custom_comments_package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"10",
          "description"=>"<p>EDITA TUS FOTOS CON NUESTRO EQUIPO DE DISEÑADORES.<br>pasos a seguir:<br><br>-Link=>(debes adjuntar un link de&nbsp;tus archivos de preferencia en mega en donde no solo tengas tus archivos y un archivo de texto detallando tus ideas).<br><br>-email 1=>corresponde a tu contacto para poder enviarte los diseños o contactarte de ser necesario.<br>-email 2=>en caso que no logremos contactar con usted por el primeo.</p><p><strong>Importante=>Procure </strong>sus fotos con alta resolucion seguido de la frase que desees que agreguemos a la misma, para logos o firmas se agradece que tengas el formato PNG.</p><p><br data-cke-eol=\"1\"></p>",
          "created_at"=>"2021-03-25 02:23:48",
          "updated_at"=>"2021-03-25 02:23:48"
        ],
        [
          "id"=>"53",
          "package_name"=>"Edicion de fotos (+ frase + logo) x 50 📷 🔥🌟",
          "categories_id"=>"21",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"175",
          "status"=>"1",
          "type_services"=>"custom_comments_package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"11",
          "description"=>"<p>EDITA TUS FOTOS CON NUESTRO EQUIPO DE DISEÑADORES.<br>pasos a seguir:<br><br>-Link=>(debes adjuntar un link de&nbsp;tus archivos de preferencia en mega en donde no solo tengas tus archivos y un archivo de texto detallando tus ideas).<br><br>-email 1=>corresponde a tu contacto para poder enviarte los diseños o contactarte de ser necesario.<br>-email 2=>en caso que no logremos contactar con usted por el primeo.</p><p><strong>Importante=>Procure </strong>sus fotos con alta resolucion seguido de la frase que desees que agreguemos a la misma, para logos o firmas se agradece que tengas el formato PNG.</p><p><br data-cke-eol=\"1\"></p>",
          "created_at"=>"2021-03-25 02:24:27",
          "updated_at"=>"2021-03-25 02:24:27"
        ],
        [
          "id"=>"54",
          "package_name"=>"Edicion de fotos (+ frase + logo) x 100 📷 🔥🌟⚡",
          "categories_id"=>"21",
          "minimum_amount"=>"1",
          "maximum_amount"=>"1",
          "price"=>"300",
          "status"=>"1",
          "type_services"=>"custom_comments_package",
          "input_adicionales"=>"[\"link\"]",
          "drip_feed"=>"0",
          "type"=>"API",
          "api_provide_name"=>"8",
          "api_service_id"=>"12",
          "description"=>"<p>EDITA TUS FOTOS CON NUESTRO EQUIPO DE DISEÑADORES.<br>pasos a seguir:<br><br>-Link=>(debes adjuntar un link de&nbsp;tus archivos de preferencia en mega en donde no solo tengas tus archivos y un archivo de texto detallando tus ideas).<br><br>-email 1=>corresponde a tu contacto para poder enviarte los diseños o contactarte de ser necesario.<br>-email 2=>en caso que no logremos contactar con usted por el primeo.</p><p><strong>Importante=>Procure </strong>sus fotos con alta resolucion seguido de la frase que desees que agreguemos a la misma, para logos o firmas se agradece que tengas el formato PNG.</p><p><br data-cke-eol=\"1\"></p>",
          "created_at"=>"2021-03-25 02:25:06",
          "updated_at"=>"2021-03-25 02:25:06"
        ]
      

    ];
    foreach ($arrayService as $service ) {
        Service::create($service);
    }
  }
}
